<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PortalNacionalGobernanzaMusical.Domain\PortalNacionalGobernanzaMusical.Domain.csproj" />
    <ProjectReference Include="..\PortalNacionalGobernanzaMusical.Shared\PortalNacionalGobernanzaMusical.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
<PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
